apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  namespace: default
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      imagePullSecrets:
        - name: dockerhub-credentials
      containers:
        - name: node
          image: dennar/node:latest
          command: ["build"]
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
